### PR TITLE
Support gensim4 LdaModel

### PR DESCRIPTION
**Pull request by larsgrobe**
Resolves NLeSC/litstudy#70

The name of the module providing LDA model support has changed between versions 3 and 4 of gensim. Besides that, the call to `LdaModel()` had to be modified.

### CODE REVIEW

**Comment by isazi** [comment]
If you could run [black](https://pypi.org/project/black/) and commit, that would fix the only failing test in the CI.

**Comment by isazi** [comment]
Thanks @larsgrobe , is the pull request ready to be merged at this point, or are you still working on it?

**Comment by larsgrobe** [comment]
It should be ready, at least I am using the code as such. Note that I also added the "ensemble LDA model", which aims at getting more stable topics from the LDA algorithm. This would need documentation, the concept is decribed here:

BRIGL, Tobias, 2019, Extracting Reliable Topics using Ensemble Latent Dirichlet Allocation [Bachelor Thesis]. Technische Hochschule Ingolstadt. Munich: Data Reply GmbH. Supervised by Alex Loosley. Available from: https://www.sezanzeb.de/machine_learning/ensemble_LDA/

Best, Lars.

**Comment by stijnh** [comment]
Great! Thanks for your contributions. I am very happy to see support for the new ensemble LDA. I would like to have more topic modeling algorithms in litstudy that have been developed in recent years. 

I have you have more ideas on topic modeling or are experimenting with other NLP processing techniques, do not hesitate to open a pull request, discussions, or issue to discuss your idea or your findings!

**Pull request merged**
